### ISSUE TITLE
资源共用问题

### ISSUE THREAD

**Issue by zhulangren** [xtqqksszml/zcode-AssetBundlePacker#10]
当两个预设b和c同时依赖资源a，b包含资源a而c引用了b上的资源a，也就是说资源a只需要在内存创建一份就可以了。
现在的情况是无论b和c分开打包还是打包一块都会创建两个资源a在内存，请问有思路解决下吗？
资源商店的BundleManager只会创建一份a在内存但是它使用的api太旧了

**Comment by xtqqksszml** [comment]
这种情况只要a单独打包就好了

**Comment by zhulangren** [comment]
下面是我的资源结构 assets/uiresources/bingzhong/showmodel/mainui_ab在内存会被创建两份，是我哪里设置的不对吗？
   Info_326:
      Name: assets/uiresources/mainui_ab
      Dependencies:
        Dependency_0: assets/language/cnui_ab
        Dependency_1: assets/uiresources/bingzhong/showmodel/mainui_ab
    Info_328:
      Name: assets/uiresources/tx_zhuantai_ab
      Dependencies:
        Dependency_0: assets/uiresources/bingzhong/showmodel/mainui_ab

**Comment by zhulangren** [comment]
感谢回复，重新测试了下，是因为我的资源缓存被删除了才创建了多份
