### ISSUE TITLE
求详细教程啊～

### ISSUE THREAD

**Issue by SamuelZon258** [xtqqksszml/zcode-AssetBundlePacker#12]
有点小白 选中一个文件夹 里面有.png .txt .lua  文件夹选Folder 然后保存规则 打包windows 打不出ab --顺便说下我是osx

**Comment by zhulangren** [comment]
unity针对文本只支持固定的后缀txt或xml，你修改后缀就可以了
  public static readonly string BUILD_PATH = System.IO.Directory.GetCurrentDirectory() + "\\" + Common.ROOT_FOLDER_NAME;

public static readonly string BUILD_PATH = System.IO.Directory.GetCurrentDirectory() + "/" + Common.ROOT_FOLDER_NAME;
修改下这个路径分隔符

**Comment by SamuelZon258** [comment]
luaframework有打包lua成ab,我打算参考下,它是遍历文件夹打包进去的

**Comment by xtqqksszml** [comment]
项目中有详细的例子，Unity打开后菜单里也有详细的说明
