### ISSUE TITLE
资源初始化

### ISSUE THREAD

**Issue by zhulangren** [xtqqksszml/zcode-AssetBundlePacker#14]
初始化时没必要把所有资源从INITIAL_PATH copy到PATH，资源量一旦增多会需要很长时间，加载资源时做个判断首先从PATH找不存在再去INITIAL_PATH 找

**Comment by xtqqksszml** [comment]
谢谢你的意见，INITIAL_PATH是指需要在安装完APP后第一次启动的时候做一次性拷贝操作，后续的版本更新并不会重复的拷贝，你所说的应该再增加一个功能用于表示是否在第一次加载时拷贝，但也会涉及到后续资源使用下载判定（判断包里的初始化资源是否是最新，不是再做拷贝）
不过最近比较忙，有空的时候可以考虑加上去
