### ISSUE TITLE
问个问题，从服务器下载更新内容，发现下载内容过多时就会卡死，没有任何报错log

### ISSUE THREAD

**Issue by youxibuhaowana** [xtqqksszml/zcode-AssetBundlePacker#18]
在使用过程中，发现更新文件过多时导致卡死，下载内容比较少时没有问题，下面是我做得实验: 
     只下载3个文件时, 可以正常使用
    只下载5个文件时, 可以正常使用
    只下载8个文件时, 无法使用，卡死

想问下需要设置 CONCURRENCE_DOWNLOAD_NUMBER 变量吗？ 还是那个地方需要配置?

我是在pc上面测试的，而且文件服务器是自己搭建的，不确定是否是服务器的问题，反复测试过少量文件的下载没有问题

**Comment by youxibuhaowana** [comment]
当把 public const int CONCURRENCE_DOWNLOAD_NUMBER = 1; 时， 不管更新内容有多大都能够正常下载

怀疑多线程时有死锁的产生

**Comment by alucard-dracula** [comment]
不用怀疑了 确定是多线程死锁

**Comment by xtqqksszml** [comment]
最新版本多线程问题已经修复了
