### ISSUE TITLE
可以支持高清资源和非高清的分类吗？

### ISSUE THREAD

**Issue by zhulangren** [xtqqksszml/zcode-AssetBundlePacker#2]
打包粒度变量搜索了几遍了只看到在编辑显示用了一下没有实际作用，可以讲解一下吗？
另外可以添加通过判断资源版本号来判断是否需要更新的实例吗？
如果再增加高清资源和非高清的分类下载就完美了，
找了很多资源管理这个是最完整的了，感谢作者分享

**Comment by xtqqksszml** [comment]
打包粒度只是一个显示参考用于优化自身项目的资源打包方式的，并不提供具体的优化功能
更新可以从两个方式入手，一个是资源号的更新，另一个是资源包下载(资源版本号可以通过AssetBundleBrowse窗口配置，资源包也通过资源包窗口创建，资源包的下载需要在自身业务逻辑中调用)
高清资源与非高清资源分类下载具体指的是什么呢，能否描述详细些，可以发我邮箱，我先了解看看
