### ISSUE TITLE
ResourcesManager.cs下的 Load()函数

### ISSUE THREAD

**Issue by wxwlog** [xtqqksszml/zcode-AssetBundlePacker#5]
ResourcesManager.cs下的 Load()函数在加载资源时，如果是编辑器模式，loadPattern.ResourcesLoadPattern等于AssetBundle ,不是EditorAsset

**Comment by xtqqksszml** [comment]
可以修改LoadPattern通过UNITY_EDITOR的宏修改加载策略，如

        /// <summary>
        /// 资源加载方式
        /// </summary>
        public emLoadPattern ResourcesLoadPattern
        {
            get
            {
#if UNITY_EDITOR
                return emLoadPattern.EditorAsset;
#else
                return emLoadPattern.All;
#endif

            }
        }

        /// <summary>
        /// 场景加载方式
        /// </summary>
        public emLoadPattern SceneLoadPattern
        {
            get
            {
#if UNITY_EDITOR
                return emLoadPattern.EditorAsset;
#else
                return emLoadPattern.All;
#endif
            }
        }
    }
