### ISSUE TITLE
打包太慢了

### ISSUE THREAD

**Issue by zhulangren** [xtqqksszml/zcode-AssetBundlePacker#6]
有办法判断不需要更新的assetbundle吗？现在资源一旦增多打包太慢了，我的资源得一个上午才能出来，并且重复资源会重复打包除非把用到它们的prefab打包成一个文件，有办法优化一下吗？

**Comment by zhulangren** [comment]
重复的资源可以挑选出来单独打包一个预设，依赖关系unity可以自动形成，打包慢的问题如果能解决就好了

**Comment by xtqqksszml** [comment]
资源增加打包慢确实是一个问题。
